services:
    mysql:
        image: mysql:8.0
        hostname: mysql
        environment:
            MYSQL_DATABASE: howsy
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
    php-fpm:
        image: webdevops/php-dev:7.4
        hostname: php-fpm
        volumes:
            - "./:/app"
        working_dir: "/app"
        depends_on:
            - mysql
    nginx:
        image: webdevops/nginx
        hostname: nginx
        environment:
            WEB_DOCUMENT_ROOT: /app/public
            WEB_DOCUMENT_INDEX: index.php
            WEB_PHP_SOCKET: php-fpm:9000
        ports:
            - "80:80"
        volumes:
            - "./:/app"
        depends_on:
            - php-fpm